### ISSUE TITLE
Trouble starting the game  "No :main namespace specified"

### ISSUE THREAD

**Issue by redroote** [OrBaruk/squares-lgj#1]
Hi,
I was trying to run this game on my OSX.

I encountered following error when I try to run the game via  " lein run figwheel"

" No :main namespace specified in project.clj "

**Comment by OrBaruk** [comment]
The correct command to run the game via figwheel is actually, I'll fix the readme
```
lein figwheel
```

**Comment by redroote** [comment]
Thank you, now I can run it.
I appreciate it.
